In [26]:
import pandas as pd

In [27]:
import numpy as np

In [28]:
df = pd.read_csv("dirtydata - dirtydata.csv")

In [29]:
df.head()

   Duration         Date  Pulse  Maxpulse  Calories
0        60  2020/12/01'    110       130     409.1
1        60  2020/12/02'    117       145     479.0
2        60  2020/12/03'    103       135     340.0
3        45  2020/12/04'    109       175     282.4
4        45  2020/12/05'    117       148     406.0

In [30]:
df.shape

(32, 5)

In [31]:
df.describe()

         Duration       Pulse    Maxpulse    Calories
count   32.000000   32.000000   32.000000   30.000000
mean    68.437500  103.500000  128.500000  266.013333
std     70.039591    7.832933   12.998759  164.876415
min     30.000000   90.000000  101.000000 -300.000000
25%     60.000000  100.000000  120.000000  247.000000
50%     60.000000  102.500000  127.500000  282.200000
75%     60.000000  106.500000  132.250000  343.975000
max    450.000000  130.000000  175.000000  479.000000

In [32]:
df.isnull().sum()

Duration    0
Date        1
Pulse       0
Maxpulse    0
Calories    2
dtype: int64

In [33]:
df.count()

Duration    32
Date        31
Pulse       32
Maxpulse    32
Calories    30
dtype: int64

In [34]:
df.dtypes

Duration      int64
Date         object
Pulse         int64
Maxpulse      int64
Calories    float64
dtype: object

In [35]:
df["Calories"] = df['Calories'].abs()

In [36]:
# df.Calories

In [37]:
df

    Duration         Date  Pulse  Maxpulse  Calories
0         60  2020/12/01'    110       130     409.1
1         60  2020/12/02'    117       145     479.0
2         60  2020/12/03'    103       135     340.0
3         45  2020/12/04'    109       175     282.4
4         45  2020/12/05'    117       148     406.0
5         60  2020/12/06'    102       127     300.0
6         60  2020/12/07'    110       136     374.0
7        450  2020/12/08'    104       134     253.3
8         30  2020/12/09'    109       133     195.1
9         60  2020/12/10'     98       124     269.0
10        60  2020/12/11'    103       147     329.3
11        60  2020/12/12'    100       120     250.7
12        60  2020/12/12'    100       120     250.7
13        60  2020/12/13'    106       128     345.3
14        60  2020/12/14'    104       132     379.3
15        60  2020/12/15'     98       123     275.0
16        60  2020/12/16'     98       120     215.2
17        60  2020/12/17'    100       120     300.0
18        45  2020/12/18'     90       112       NaN
19        60  2020/12/19'    103       123     323.0
20        45  2020/12/20'     97       125     243.0
21        60  2020/12/21'    108       131     364.2
22        45          NaN    100       119     282.0
23        60  2020/12/23'    130       101     300.0
24        45  2020/12/24'    105       132     246.0
25        60  2020/12/25'    102       126     334.5
26        60     20201226    100       120     250.0
27        60  2020/12/27'     92       118     241.0
28        60  2020/12/28'    103       132       NaN
29        60  2020/12/29'    100       132     280.0
30        60  2020/12/30'    102       129     380.3
31        60  2020/12/31'     92       115     243.0

In [38]:
x = df.Calories.mean()

In [39]:
x

304.68

In [40]:
df['Calories'].fillna(x,inplace=True)

In [41]:
df.isnull().sum()

Duration    0
Date        1
Pulse       0
Maxpulse    0
Calories    0
dtype: int64

In [42]:
df.dropna(subset=["Date"],inplace=True)

In [43]:
df.isnull().sum()

Duration    0
Date        0
Pulse       0
Maxpulse    0
Calories    0
dtype: int64

In [44]:
df.dtypes

Duration      int64
Date         object
Pulse         int64
Maxpulse      int64
Calories    float64
dtype: object

In [45]:
df['Calories'] = df['Calories'].astype(int)

In [46]:
df.Calories.dtype

dtype('int32')

In [47]:
df['Date'] = df['Date'].apply(lambda x: x[:-1] if x.endswith("'") else x)
df['Date'][:5]

0    2020/12/01
1    2020/12/02
2    2020/12/03
3    2020/12/04
4    2020/12/05
Name: Date, dtype: object

In [49]:
df.Date

0     2020/12/01
1     2020/12/02
2     2020/12/03
3     2020/12/04
4     2020/12/05
5     2020/12/06
6     2020/12/07
7     2020/12/08
8     2020/12/09
9     2020/12/10
10    2020/12/11
11    2020/12/12
12    2020/12/12
13    2020/12/13
14    2020/12/14
15    2020/12/15
16    2020/12/16
17    2020/12/17
18    2020/12/18
19    2020/12/19
20    2020/12/20
21    2020/12/21
23    2020/12/23
24    2020/12/24
25    2020/12/25
26      20201226
27    2020/12/27
28    2020/12/28
29    2020/12/29
30    2020/12/30
31    2020/12/31
Name: Date, dtype: object

In [50]:
df['Date'] = df['Date'].apply(lambda x: x.split("/"))
df.Date

0     [2020, 12, 01]
1     [2020, 12, 02]
2     [2020, 12, 03]
3     [2020, 12, 04]
4     [2020, 12, 05]
5     [2020, 12, 06]
6     [2020, 12, 07]
7     [2020, 12, 08]
8     [2020, 12, 09]
9     [2020, 12, 10]
10    [2020, 12, 11]
11    [2020, 12, 12]
12    [2020, 12, 12]
13    [2020, 12, 13]
14    [2020, 12, 14]
15    [2020, 12, 15]
16    [2020, 12, 16]
17    [2020, 12, 17]
18    [2020, 12, 18]
19    [2020, 12, 19]
20    [2020, 12, 20]
21    [2020, 12, 21]
23    [2020, 12, 23]
24    [2020, 12, 24]
25    [2020, 12, 25]
26        [20201226]
27    [2020, 12, 27]
28    [2020, 12, 28]
29    [2020, 12, 29]
30    [2020, 12, 30]
31    [2020, 12, 31]
Name: Date, dtype: object

In [52]:
df['Date'] = df['Date'].apply(lambda x: "".join(x))
df.Date

0     20201201
1     20201202
2     20201203
3     20201204
4     20201205
5     20201206
6     20201207
7     20201208
8     20201209
9     20201210
10    20201211
11    20201212
12    20201212
13    20201213
14    20201214
15    20201215
16    20201216
17    20201217
18    20201218
19    20201219
20    20201220
21    20201221
23    20201223
24    20201224
25    20201225
26    20201226
27    20201227
28    20201228
29    20201229
30    20201230
31    20201231
Name: Date, dtype: object

In [54]:
df['Date'] = pd.to_datetime(df['Date'])
df.Date

0    2020-12-01
1    2020-12-02
2    2020-12-03
3    2020-12-04
4    2020-12-05
5    2020-12-06
6    2020-12-07
7    2020-12-08
8    2020-12-09
9    2020-12-10
10   2020-12-11
11   2020-12-12
12   2020-12-12
13   2020-12-13
14   2020-12-14
15   2020-12-15
16   2020-12-16
17   2020-12-17
18   2020-12-18
19   2020-12-19
20   2020-12-20
21   2020-12-21
23   2020-12-23
24   2020-12-24
25   2020-12-25
26   2020-12-26
27   2020-12-27
28   2020-12-28
29   2020-12-29
30   2020-12-30
31   2020-12-31
Name: Date, dtype: datetime64[ns]

In [55]:
nc = df.columns

In [56]:
nc

Index(['Duration', 'Date', 'Pulse', 'Maxpulse', 'Calories'], dtype='object')

In [57]:
for col in nc:
    col_zscore = col + '_zscore'
    df[col_zscore] = (df[col] - df[col].mean())/df[col].std(ddof=0)  
df

,Duration,Date,Pulse,Maxpulse,Calories,Duration_zscore,Date_zscore,Pulse_zscore,Maxpulse_zscore,Calories_zscore
0,60,2020-12-01,110,130,409,-0.131508,-1.648724,0.818140,0.092648,1.628571
1,60,2020-12-02,117,145,479,-0.131508,-1.536393,1.714788,1.257005,2.727109
2,60,2020-12-03,103,135,340,-0.131508,-1.424063,-0.078508,0.480767,0.545726
3,45,2020-12-04,109,175,282,-0.346073,-1.311732,0.690047,3.585719,-0.364492
4,45,2020-12-05,117,148,406,-0.346073,-1.199401,1.714788,1.489876,1.581491
5,60,2020-12-06,102,127,300,-0.131508,-1.087071,-0.206601,-0.140224,-0.082011
6,60,2020-12-07,110,136,374,-0.131508,-0.974740,0.818140,0.558391,1.079302
7,450,2020-12-08,104,134,253,5.447182,-0.862409,0.049584,0.403143,-0.819601
8,30,2020-12-09,109,133,195,-0.560638,-0.750079,0.690047,0.325519,-1.729819
9,60,2020-12-10,98,124,269,-0.131508,-0.637748,-0.718971,-0.373095,-0.568506
10,60,2020-12-11,103,147,329,-0.131508,-0.525418,-0.078508,1.412253,0.373098
11,60,2020-12-12,100,120,250,-0.131508,-0.413087,-0.462786,-0.683590,-0.866681
12,60,2020-12-12,100,120,250,-0.131508,-0.413087,-0.462786,-0.683590,-0.866681
13,60,2020-12-13,106,128,345,-0.131508,-0.300756,0.305769,-0.062600,0.624193
14,60,2020-12-14,104,132,379,-0.131508,-0.188426,0.049584,0.247895,1.157769
15,60,2020-12-15,98,123,275,-0.131508,-0.076095,-0.718971,-0.450719,-0.474346
16,60,2020-12-16,98,120,215,-0.131508,0.036236,-0.718971,-0.683590,-1.415950
17,60,2020-12-17,100,120,300,-0.131508,0.148566,-0.462786,-0.683590,-0.082011
18,45,2020-12-18,90,112,304,-0.346073,0.260897,-1.743712,-1.304581,-0.019237
19,60,2020-12-19,103,123,323,-0.131508,0.373228,-0.078508,-0.450719,0.278938
20,45,2020-12-20,97,125,243,-0.346073,0.485558,-0.847064,-0.295471,-0.976535
21,60,2020-12-21,108,131,364,-0.131508,0.597889,0.561955,0.170272,0.922367
23,60,2020-12-23,130,101,300,-0.131508,0.822550,3.379992,-2.158443,-0.082011
24,45,2020-12-24,105,132,246,-0.346073,0.934881,0.177677,0.247895,-0.929455
25,60,2020-12-25,102,126,334,-0.131508,1.047211,-0.206601,-0.217847,0.451565
26,60,2020-12-26,100,120,250,-0.131508,1.159542,-0.462786,-0.683590,-0.866681
27,60,2020-12-27,92,118,241,-0.131508,1.271873,-1.487527,-0.838838,-1.007922
28,60,2020-12-28,103,132,304,-0.131508,1.384203,-0.078508,0.247895,-0.019237
29,60,2020-12-29,100,132,280,-0.131508,1.496534,-0.462786,0.247895,-0.395879
30,60,2020-12-30,102,129,380,-0.131508,1.608865,-0.206601,0.015024,1.173462
31,60,2020-12-31,92,115,243,-0.131508,1.721195,-1.487527,-1.071709,-0.976535

In [59]:
from scipy.stats import zscore

In [75]:
df_z = df.drop('Date',axis=1)
df_z

,Duration,Pulse,Maxpulse,Calories,Duration_zscore,Date_zscore,Pulse_zscore,Maxpulse_zscore,Calories_zscore
0,60,110,130,409,-0.131508,-1.648724,0.818140,0.092648,1.628571
1,60,117,145,479,-0.131508,-1.536393,1.714788,1.257005,2.727109
2,60,103,135,340,-0.131508,-1.424063,-0.078508,0.480767,0.545726
3,45,109,175,282,-0.346073,-1.311732,0.690047,3.585719,-0.364492
4,45,117,148,406,-0.346073,-1.199401,1.714788,1.489876,1.581491
5,60,102,127,300,-0.131508,-1.087071,-0.206601,-0.140224,-0.082011
6,60,110,136,374,-0.131508,-0.974740,0.818140,0.558391,1.079302
7,450,104,134,253,5.447182,-0.862409,0.049584,0.403143,-0.819601
8,30,109,133,195,-0.560638,-0.750079,0.690047,0.325519,-1.729819
9,60,98,124,269,-0.131508,-0.637748,-0.718971,-0.373095,-0.568506
10,60,103,147,329,-0.131508,-0.525418,-0.078508,1.412253,0.373098
11,60,100,120,250,-0.131508,-0.413087,-0.462786,-0.683590,-0.866681
12,60,100,120,250,-0.131508,-0.413087,-0.462786,-0.683590,-0.866681
13,60,106,128,345,-0.131508,-0.300756,0.305769,-0.062600,0.624193
14,60,104,132,379,-0.131508,-0.188426,0.049584,0.247895,1.157769
15,60,98,123,275,-0.131508,-0.076095,-0.718971,-0.450719,-0.474346
16,60,98,120,215,-0.131508,0.036236,-0.718971,-0.683590,-1.415950
17,60,100,120,300,-0.131508,0.148566,-0.462786,-0.683590,-0.082011
18,45,90,112,304,-0.346073,0.260897,-1.743712,-1.304581,-0.019237
19,60,103,123,323,-0.131508,0.373228,-0.078508,-0.450719,0.278938
20,45,97,125,243,-0.346073,0.485558,-0.847064,-0.295471,-0.976535
21,60,108,131,364,-0.131508,0.597889,0.561955,0.170272,0.922367
23,60,130,101,300,-0.131508,0.822550,3.379992,-2.158443,-0.082011
24,45,105,132,246,-0.346073,0.934881,0.177677,0.247895,-0.929455
25,60,102,126,334,-0.131508,1.047211,-0.206601,-0.217847,0.451565
26,60,100,120,250,-0.131508,1.159542,-0.462786,-0.683590,-0.866681
27,60,92,118,241,-0.131508,1.271873,-1.487527,-0.838838,-1.007922
28,60,103,132,304,-0.131508,1.384203,-0.078508,0.247895,-0.019237
29,60,100,132,280,-0.131508,1.496534,-0.462786,0.247895,-0.395879
30,60,102,129,380,-0.131508,1.608865,-0.206601,0.015024,1.173462
31,60,92,115,243,-0.131508,1.721195,-1.487527,-1.071709,-0.976535

In [76]:
df_z.apply(zscore)

,Duration,Pulse,Maxpulse,Calories,Duration_zscore,Date_zscore,Pulse_zscore,Maxpulse_zscore,Calories_zscore
0,-0.131508,0.818140,0.092648,1.628571,-0.131508,-1.648724,0.818140,0.092648,1.628571
1,-0.131508,1.714788,1.257005,2.727109,-0.131508,-1.536393,1.714788,1.257005,2.727109
2,-0.131508,-0.078508,0.480767,0.545726,-0.131508,-1.424063,-0.078508,0.480767,0.545726
3,-0.346073,0.690047,3.585719,-0.364492,-0.346073,-1.311732,0.690047,3.585719,-0.364492
4,-0.346073,1.714788,1.489876,1.581491,-0.346073,-1.199401,1.714788,1.489876,1.581491
5,-0.131508,-0.206601,-0.140224,-0.082011,-0.131508,-1.087071,-0.206601,-0.140224,-0.082011
6,-0.131508,0.818140,0.558391,1.079302,-0.131508,-0.974740,0.818140,0.558391,1.079302
7,5.447182,0.049584,0.403143,-0.819601,5.447182,-0.862409,0.049584,0.403143,-0.819601
8,-0.560638,0.690047,0.325519,-1.729819,-0.560638,-0.750079,0.690047,0.325519,-1.729819
9,-0.131508,-0.718971,-0.373095,-0.568506,-0.131508,-0.637748,-0.718971,-0.373095,-0.568506
10,-0.131508,-0.078508,1.412253,0.373098,-0.131508,-0.525418,-0.078508,1.412253,0.373098
11,-0.131508,-0.462786,-0.683590,-0.866681,-0.131508,-0.413087,-0.462786,-0.683590,-0.866681
12,-0.131508,-0.462786,-0.683590,-0.866681,-0.131508,-0.413087,-0.462786,-0.683590,-0.866681
13,-0.131508,0.305769,-0.062600,0.624193,-0.131508,-0.300756,0.305769,-0.062600,0.624193
14,-0.131508,0.049584,0.247895,1.157769,-0.131508,-0.188426,0.049584,0.247895,1.157769
15,-0.131508,-0.718971,-0.450719,-0.474346,-0.131508,-0.076095,-0.718971,-0.450719,-0.474346
16,-0.131508,-0.718971,-0.683590,-1.415950,-0.131508,0.036236,-0.718971,-0.683590,-1.415950
17,-0.131508,-0.462786,-0.683590,-0.082011,-0.131508,0.148566,-0.462786,-0.683590,-0.082011
18,-0.346073,-1.743712,-1.304581,-0.019237,-0.346073,0.260897,-1.743712,-1.304581,-0.019237
19,-0.131508,-0.078508,-0.450719,0.278938,-0.131508,0.373228,-0.078508,-0.450719,0.278938
20,-0.346073,-0.847064,-0.295471,-0.976535,-0.346073,0.485558,-0.847064,-0.295471,-0.976535
21,-0.131508,0.561955,0.170272,0.922367,-0.131508,0.597889,0.561955,0.170272,0.922367
23,-0.131508,3.379992,-2.158443,-0.082011,-0.131508,0.822550,3.379992,-2.158443,-0.082011
24,-0.346073,0.177677,0.247895,-0.929455,-0.346073,0.934881,0.177677,0.247895,-0.929455
25,-0.131508,-0.206601,-0.217847,0.451565,-0.131508,1.047211,-0.206601,-0.217847,0.451565
26,-0.131508,-0.462786,-0.683590,-0.866681,-0.131508,1.159542,-0.462786,-0.683590,-0.866681
27,-0.131508,-1.487527,-0.838838,-1.007922,-0.131508,1.271873,-1.487527,-0.838838,-1.007922
28,-0.131508,-0.078508,0.247895,-0.019237,-0.131508,1.384203,-0.078508,0.247895,-0.019237
29,-0.131508,-0.462786,0.247895,-0.395879,-0.131508,1.496534,-0.462786,0.247895,-0.395879
30,-0.131508,-0.206601,0.015024,1.173462,-0.131508,1.608865,-0.206601,0.015024,1.173462
31,-0.131508,-1.487527,-1.071709,-0.976535,-0.131508,1.721195,-1.487527,-1.071709,-0.976535